version: "3"

services:
  api:
    build: .
    depends_on:
      - hardhat
    environment:
      - ETHEREUM_NETWORK=http://hardhat:8545
    ports:
      - "3100:3100"
    command: npm run start

  hardhat:
    build: .
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8547:8547"
    command: npm run start:node
